### PR TITLE
[FEAT] Cancell Ticks for ERROR Machines

### LINKED ISSUE #142: [FEAT] Cancell ticks for exceptional machines
Tons exception instances lags server and spams console whereas that machine is not working proply.  

Add a monitor to tickScheduler, cancelling incoming ticks for those broken machines / tickables.

### PR DESCRIPTION
**Pull request by iceBear67**
This closes #142 

Possibly affects #86

### CODE REVIEW

**Comment by iceBear67** [comment]
Waiting for Spigot Tests

**Review by EvanLuo42 — APPROVED** [review]
Approved

**Comment by iceBear67** [comment]
It seems slower (+ 1~2 ms) than the original solution?

**Comment by iceBear67** [comment]
Possibly lagged by double try...catch  

Let's try to flatten it

**Comment by iceBear67** [comment]
By flatten the error handing architecture, 1~2 ms has been reduced.

**Pull request merged**
